image: node:10.12.0

cache:
  paths:
  - node_modules/

before_script:
- apt-get update -qq && apt-get install

stages:
- test
- build

test:
  stage: test
  before_script:
  - rm -rf .yarn
  - yarn install
  script:
  - yarn lint --fix
  - yarn test-with-coverage
  only:
  - test-deploy

build:
  stage: build
  before_script:
  - rm -rf .yarn
  - yarn install
  script:
  - yarn run gen-types
  - yarn build
