image: node:10.12.0

cache:
  paths:
  - node_modules/

before_script:
- apt-get update -qq && apt-get install

stages:
- test-build
- deployment

test:
  stage: test-build
  before_script:
  - rm -rf .yarn
  - yarn install
  script:
  - yarn test

build:
  stage: test-build
  before_script:
  - rm -rf .yarn
  - yarn install
  script:
  - yarn run gen-types
  - yarn build

deployment:
  stage: deployment
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=markt-dev --api-key=$HEROKU_API_KEY
  only:
    - master
