import {MigrationInterface, QueryRunner} from "typeorm";

export class removeRequiredId1552433207422 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_822972ceea1fda0973b8acc7bbe"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP CONSTRAINT "FK_176821f39ac7355226a95daf37e"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP CONSTRAINT "FK_c5105925e74503e07ce4479189a"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP CONSTRAINT "FK_058b8668561921969da077b0799"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP CONSTRAINT "FK_cb5304de48a2ec818c2f48f843d"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_f73c578de3c64a4e2dd368c6e6e"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP CONSTRAINT "FK_c98a2327bf856bfeb85ab3ec9d5"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP CONSTRAINT "FK_0db690743537c6817a7ec71cd32"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP CONSTRAINT "FK_9b68bdb51c6984d5c435051faea"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP CONSTRAINT "FK_794f9ac7ebf3cc04d034939356d"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP CONSTRAINT "FK_b99b84e267b8d72ea4058516cfa"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP CONSTRAINT "FK_856d7baac90f6d1af25c37d1685"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP CONSTRAINT "FK_cf5f234564677334d9b49b76af2"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP CONSTRAINT "FK_7106e9c01a6e96afaa4653feb12"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_d14692e738d6f44d064c44d87a0"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_6ef6494ecfce4b57b10d487b181"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_6dcd3411b1ed963e5fa9392c6bf"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP CONSTRAINT "FK_49737dc54aaa90c42f048dabe89"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP CONSTRAINT "FK_a1dfd5dc94529235b78eb0a3419"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP CONSTRAINT "FK_466a6c73ef04ce13adb5d4a2547"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP CONSTRAINT "FK_600674e048095f9aa4ef506e432"`);
        await queryRunner.query(`DROP INDEX "IDX_ef2fb839248017665e5033e730"`);
        await queryRunner.query(`DROP INDEX "IDX_0408cb491623b121499d4fa238"`);
        await queryRunner.query(`ALTER TABLE "institutions" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "institutions" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "external_guid"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "account_type"`);
        await queryRunner.query(`DROP TYPE "users_account_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "account_locked"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "accepted_tos"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_confirmed"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "institution_id"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "session_number"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "allow_sell"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "profit_equation"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "role_type_id"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "scenario_session_id"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "is_seller"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "player_id"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "transaction_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "buyer_profit"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "seller_profit"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "round_id"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "round_number"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "average_price"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "num_transactions"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "session_id"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "session_number"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "experiment_id"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "scenario_session_id"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP CONSTRAINT "UQ_7dc268bb2c7e4478215ec278170"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "scenario_session_id"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "session_number"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "number_of_rounds"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "scenario_id"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "round_discussion_points"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP CONSTRAINT "UQ_d557311e12c1e1718615f4e6ddc"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "scenario_code"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "max_player_size"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "session_count"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "role_distribution"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP CONSTRAINT "UQ_3f493515964092d1c2a6e94ef28"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP COLUMN "role_type_id"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP COLUMN "scenario_id"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "num_transactions"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "total_profit"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "experiment_id"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "player_id"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "role_type_id"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "player_code"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "accepted_tos"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "guide_id"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "guide_id"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP CONSTRAINT "REL_49737dc54aaa90c42f048dabe8"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "join_code"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "num_players"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "created_date"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "updated_date"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "guide_id"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "scenario_id"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "institutions" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "institutions" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "externalGuid" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastName" character varying(255)`);
        await queryRunner.query(`CREATE TYPE "users_accounttype_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "accountType" "users_accounttype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "accountLocked" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "acceptedTos" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailConfirmed" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "institutionId" uuid`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "sessionNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "allowSell" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "profitEquation" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "roleTypeId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "scenarioSessionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "isSeller" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "playerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "transactionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "buyerProfit" double precision NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "sellerProfit" double precision NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "roundId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "roundNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "averagePrice" double precision NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "numTransactions" integer NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "endDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "sessionId" uuid`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "sessionNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "endDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "experimentId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "scenarioSessionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "scenarioSessionId" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD CONSTRAINT "UQ_c7e6dfba143c383f96fa03ade43" UNIQUE ("scenarioSessionId")`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "sessionNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "roundDiscussionPoints" jsonb NOT NULL DEFAULT '[{}]'`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "numberOfRounds" integer NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "scenarioId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "scenarioCode" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD CONSTRAINT "UQ_d9e87eef99ebbe04142c03c4129" UNIQUE ("scenarioCode")`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "maxPlayerSize" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "sessionCount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "roleDistribution" jsonb NOT NULL DEFAULT '[{}]'`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD "roleTypeId" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD CONSTRAINT "UQ_fab2265bd86b9e74199e2df31a3" UNIQUE ("roleTypeId")`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD "scenarioId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "numTransactions" integer NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "totalProfit" double precision NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "experimentId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "playerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "roleTypeId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "players" ADD "playerCode" character varying(6) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "players" ADD "firstName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "players" ADD "lastName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "players" ADD "acceptedTos" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "players" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" ADD "guideId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "players" ADD "groupId" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "guideId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guides" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "guides" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "guides" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guides" ADD CONSTRAINT "UQ_6fb9ae622c0f4c05653408ee58f" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "joinCode" character varying(8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "numPlayers" integer NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "endDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "guideId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "scenarioId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "groupId" uuid`);
        await queryRunner.query(`CREATE INDEX "IDX_5372672fbfd1677205e0ce3ece" ON "users" ("firstName") `);
        await queryRunner.query(`CREATE INDEX "IDX_af99afb7cf88ce20aff6977e68" ON "users" ("lastName") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_412354ee74d15b76137f5dba3e3" FOREIGN KEY ("institutionId") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD CONSTRAINT "FK_fb584ba69be87fecafbd6c13533" FOREIGN KEY ("roleTypeId") REFERENCES "role_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD CONSTRAINT "FK_3e2d28a9fd661f8d75b59f29e39" FOREIGN KEY ("scenarioSessionId") REFERENCES "scenario_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD CONSTRAINT "FK_2d18345421b0fdf0ee128d6b602" FOREIGN KEY ("playerId") REFERENCES "experiment_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD CONSTRAINT "FK_42c4df88f1cef0d08c3d0b5cf2c" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_e43b2a215268ed5072b1564707c" FOREIGN KEY ("roundId") REFERENCES "rounds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD CONSTRAINT "FK_90a228425cd23d8762a281c3028" FOREIGN KEY ("sessionId") REFERENCES "experiment_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD CONSTRAINT "FK_b3495db983af8df760004795530" FOREIGN KEY ("experimentId") REFERENCES "experiments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD CONSTRAINT "FK_b08f13a3d524125f7fd5886f45e" FOREIGN KEY ("scenarioSessionId") REFERENCES "scenario_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD CONSTRAINT "FK_3cb767a54883f56539d83d68591" FOREIGN KEY ("scenarioId") REFERENCES "scenarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD CONSTRAINT "FK_caa25232d6cdce1e27c1d26991f" FOREIGN KEY ("scenarioId") REFERENCES "scenarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD CONSTRAINT "FK_0426d4815121f2e5709e2a67dc9" FOREIGN KEY ("experimentId") REFERENCES "experiments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD CONSTRAINT "FK_af7c340a597aac4dac704ce07b2" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD CONSTRAINT "FK_32b30099672d74f4efc395431d7" FOREIGN KEY ("roleTypeId") REFERENCES "role_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_9d97a3abbd5d29aedd7575a8cc0" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_b9f0709bb242ca2796269745d49" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_a8c61efb6ce77d3ae969273a823" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guides" ADD CONSTRAINT "FK_6fb9ae622c0f4c05653408ee58f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD CONSTRAINT "FK_e40df75c07187f62f5bd0c659ed" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD CONSTRAINT "FK_30dace05b8568a514dc8e9ff930" FOREIGN KEY ("scenarioId") REFERENCES "scenarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD CONSTRAINT "FK_65a10080a35573762add499b1e3" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "experiments" DROP CONSTRAINT "FK_65a10080a35573762add499b1e3"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP CONSTRAINT "FK_30dace05b8568a514dc8e9ff930"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP CONSTRAINT "FK_e40df75c07187f62f5bd0c659ed"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP CONSTRAINT "FK_6fb9ae622c0f4c05653408ee58f"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_a8c61efb6ce77d3ae969273a823"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_b9f0709bb242ca2796269745d49"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_9d97a3abbd5d29aedd7575a8cc0"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP CONSTRAINT "FK_32b30099672d74f4efc395431d7"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP CONSTRAINT "FK_af7c340a597aac4dac704ce07b2"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP CONSTRAINT "FK_0426d4815121f2e5709e2a67dc9"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP CONSTRAINT "FK_caa25232d6cdce1e27c1d26991f"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP CONSTRAINT "FK_3cb767a54883f56539d83d68591"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP CONSTRAINT "FK_b08f13a3d524125f7fd5886f45e"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP CONSTRAINT "FK_b3495db983af8df760004795530"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP CONSTRAINT "FK_90a228425cd23d8762a281c3028"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_e43b2a215268ed5072b1564707c"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP CONSTRAINT "FK_42c4df88f1cef0d08c3d0b5cf2c"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP CONSTRAINT "FK_2d18345421b0fdf0ee128d6b602"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP CONSTRAINT "FK_3e2d28a9fd661f8d75b59f29e39"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP CONSTRAINT "FK_fb584ba69be87fecafbd6c13533"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_412354ee74d15b76137f5dba3e3"`);
        await queryRunner.query(`DROP INDEX "IDX_af99afb7cf88ce20aff6977e68"`);
        await queryRunner.query(`DROP INDEX "IDX_5372672fbfd1677205e0ce3ece"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "groupId"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "scenarioId"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "guideId"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "numPlayers"`);
        await queryRunner.query(`ALTER TABLE "experiments" DROP COLUMN "joinCode"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP CONSTRAINT "UQ_6fb9ae622c0f4c05653408ee58f"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "guideId"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "groupId"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "guideId"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "acceptedTos"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "playerCode"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "roleTypeId"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "playerId"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "experimentId"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "totalProfit"`);
        await queryRunner.query(`ALTER TABLE "experiment_players" DROP COLUMN "numTransactions"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP COLUMN "scenarioId"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP CONSTRAINT "UQ_fab2265bd86b9e74199e2df31a3"`);
        await queryRunner.query(`ALTER TABLE "role_types" DROP COLUMN "roleTypeId"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "roleDistribution"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "sessionCount"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "maxPlayerSize"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP CONSTRAINT "UQ_d9e87eef99ebbe04142c03c4129"`);
        await queryRunner.query(`ALTER TABLE "scenarios" DROP COLUMN "scenarioCode"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "scenarioId"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "numberOfRounds"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "roundDiscussionPoints"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "sessionNumber"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP CONSTRAINT "UQ_c7e6dfba143c383f96fa03ade43"`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" DROP COLUMN "scenarioSessionId"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "scenarioSessionId"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "experimentId"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" DROP COLUMN "sessionNumber"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "numTransactions"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "averagePrice"`);
        await queryRunner.query(`ALTER TABLE "rounds" DROP COLUMN "roundNumber"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "roundId"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "sellerProfit"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "buyerProfit"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "transactionId"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "playerId"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "player_transactions" DROP COLUMN "isSeller"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "scenarioSessionId"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "roleTypeId"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "profitEquation"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "allowSell"`);
        await queryRunner.query(`ALTER TABLE "session_roles" DROP COLUMN "sessionNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "institutionId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailConfirmed"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "acceptedTos"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "accountLocked"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "accountType"`);
        await queryRunner.query(`DROP TYPE "users_accounttype_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "externalGuid"`);
        await queryRunner.query(`ALTER TABLE "institutions" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "institutions" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "group_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "scenario_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "guide_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "end_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "num_players" integer NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD "join_code" character varying(8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guides" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guides" ADD CONSTRAINT "REL_49737dc54aaa90c42f048dabe8" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "guides" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "guides" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "guide_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" ADD "group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "players" ADD "guide_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "players" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" ADD "accepted_tos" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "players" ADD "last_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "players" ADD "first_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "players" ADD "player_code" character varying(6) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "role_type_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "player_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "experiment_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "total_profit" double precision NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD "num_transactions" integer NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD "scenario_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD "role_type_id" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD CONSTRAINT "UQ_3f493515964092d1c2a6e94ef28" UNIQUE ("role_type_id")`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "role_distribution" jsonb NOT NULL DEFAULT '[{}]'`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "session_count" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "max_player_size" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD "scenario_code" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenarios" ADD CONSTRAINT "UQ_d557311e12c1e1718615f4e6ddc" UNIQUE ("scenario_code")`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "round_discussion_points" jsonb NOT NULL DEFAULT '[{}]'`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "scenario_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "number_of_rounds" integer NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "session_number" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD "scenario_session_id" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD CONSTRAINT "UQ_7dc268bb2c7e4478215ec278170" UNIQUE ("scenario_session_id")`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "scenario_session_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "experiment_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "end_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD "session_number" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "session_id" uuid`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "end_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "num_transactions" integer NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "average_price" double precision NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD "round_number" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "round_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "seller_profit" double precision NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "buyer_profit" double precision NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "transaction_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "player_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD "is_seller" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "scenario_session_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "role_type_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "profit_equation" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "allow_sell" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD "session_number" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "institution_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_confirmed" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "accepted_tos" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "account_locked" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "users_account_type_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "account_type" "users_account_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "external_guid" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "institutions" ADD "updated_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "institutions" ADD "created_date" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_0408cb491623b121499d4fa238" ON "users" ("last_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef2fb839248017665e5033e730" ON "users" ("first_name") `);
        await queryRunner.query(`ALTER TABLE "experiments" ADD CONSTRAINT "FK_600674e048095f9aa4ef506e432" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD CONSTRAINT "FK_466a6c73ef04ce13adb5d4a2547" FOREIGN KEY ("scenario_id") REFERENCES "scenarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiments" ADD CONSTRAINT "FK_a1dfd5dc94529235b78eb0a3419" FOREIGN KEY ("guide_id") REFERENCES "guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guides" ADD CONSTRAINT "FK_49737dc54aaa90c42f048dabe89" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_6dcd3411b1ed963e5fa9392c6bf" FOREIGN KEY ("guide_id") REFERENCES "guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_6ef6494ecfce4b57b10d487b181" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_d14692e738d6f44d064c44d87a0" FOREIGN KEY ("guide_id") REFERENCES "guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD CONSTRAINT "FK_7106e9c01a6e96afaa4653feb12" FOREIGN KEY ("role_type_id") REFERENCES "role_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD CONSTRAINT "FK_cf5f234564677334d9b49b76af2" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_players" ADD CONSTRAINT "FK_856d7baac90f6d1af25c37d1685" FOREIGN KEY ("experiment_id") REFERENCES "experiments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_types" ADD CONSTRAINT "FK_b99b84e267b8d72ea4058516cfa" FOREIGN KEY ("scenario_id") REFERENCES "scenarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scenario_sessions" ADD CONSTRAINT "FK_794f9ac7ebf3cc04d034939356d" FOREIGN KEY ("scenario_id") REFERENCES "scenarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD CONSTRAINT "FK_9b68bdb51c6984d5c435051faea" FOREIGN KEY ("scenario_session_id") REFERENCES "scenario_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_sessions" ADD CONSTRAINT "FK_0db690743537c6817a7ec71cd32" FOREIGN KEY ("experiment_id") REFERENCES "experiments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rounds" ADD CONSTRAINT "FK_c98a2327bf856bfeb85ab3ec9d5" FOREIGN KEY ("session_id") REFERENCES "experiment_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_f73c578de3c64a4e2dd368c6e6e" FOREIGN KEY ("round_id") REFERENCES "rounds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD CONSTRAINT "FK_cb5304de48a2ec818c2f48f843d" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transactions" ADD CONSTRAINT "FK_058b8668561921969da077b0799" FOREIGN KEY ("player_id") REFERENCES "experiment_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD CONSTRAINT "FK_c5105925e74503e07ce4479189a" FOREIGN KEY ("scenario_session_id") REFERENCES "scenario_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_roles" ADD CONSTRAINT "FK_176821f39ac7355226a95daf37e" FOREIGN KEY ("role_type_id") REFERENCES "role_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_822972ceea1fda0973b8acc7bbe" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
